import { ArrowLeftOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Checkbox, Layout, Modal, Space, Table, Tag, Typography, message } from 'antd';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { can, hasRole } from '../auth/permissions.js';
import { useCurrentUser } from '../auth/useAuth.js';
import { useAccessPermissions, useAccessRoles, useAccessUsers, useUpdateUserRoles } from './useAccessControl.js';
const {Title,Text}=Typography;

export default function AccessControlPage(){
 const navigate=useNavigate(),{data:me}=useCurrentUser(),users=useAccessUsers(),roles=useAccessRoles(),permissions=useAccessPermissions(),update=useUpdateUserRoles(),[editing,setEditing]=useState(null),[selected,setSelected]=useState([]),[api,holder]=message.useMessage();
 const roleOptions=useMemo(()=>{const names=(roles.data||[]).map(r=>r.name);return hasRole(me,'Owner')?names:names.filter(r=>r!=='Owner');},[roles.data,me]);
 const openEditor=u=>{setEditing(u);setSelected((u.roles||[]).map(r=>typeof r==='string'?r:r.name));};
 const save=()=>{if(!editing||selected.length===0)return;Modal.confirm({title:'Confirm role change',content:`Update access roles for ${editing.name || editing.email}? This changes the user’s effective permissions immediately.`,okText:'Update access',onOk:async()=>{try{await update.mutateAsync({userId:editing.id,roles:selected});api.success('User access updated');setEditing(null);}catch(error){api.error(error?.response?.data?.message||'Access update failed.');}}});};
 const columns=[{title:'User',render:(_,u)=><div><Text strong>{u.name}</Text><br/><Text type="secondary">{u.email}</Text></div>},{title:'Roles',render:(_,u)=><Space wrap>{(u.roles||[]).map(r=><Tag key={r.id||r.name}>{r.name||r}</Tag>)}</Space>},{title:'Actions',render:(_,u)=>can(me,'roles.manage')?<Button onClick={()=>openEditor(u)}>Manage roles</Button>:null}];
 const matrixColumns=[{title:'Permission',dataIndex:'permission',fixed:'left'},...(roles.data||[]).map(role=>({title:role.name,key:role.name,align:'center',render:(_,row)=>role.permissions.includes(row.permission)?'✓':'—'}))];
 const matrix=(permissions.data||[]).map(permission=>({key:permission,permission}));
 return <Layout className="workspace-shell">{holder}<Layout><Layout.Header className="workspace-header"><Space><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/')}>Knowledge library</Button><SafetyCertificateOutlined/><Text strong>Access Control</Text></Space></Layout.Header><Layout.Content className="workspace-content"><section className="library-heading"><div><Text className="eyebrow">ADMINISTRATION</Text><Title level={1} className="library-title">Access Control</Title><Text type="secondary">Manage workspace roles while the backend remains the authoritative security boundary.</Text></div></section><Alert type="info" showIcon message="Owner protection" description="Only Owners can manage the Owner role, and the final Owner cannot lose Owner access." style={{marginBottom:20}}/><Card title="Users" className="state-card"><Table rowKey="id" loading={users.isLoading} dataSource={users.data?.data||[]} columns={columns} pagination={false} scroll={{x:700}}/></Card><Card title="Permission matrix" className="state-card" style={{marginTop:20}}><Table rowKey="permission" loading={roles.isLoading||permissions.isLoading} dataSource={matrix} columns={matrixColumns} pagination={false} scroll={{x:800}} size="small"/></Card><Modal title="Manage user roles" open={Boolean(editing)} onCancel={()=>!update.isPending&&setEditing(null)} onOk={save} okText="Review & update" confirmLoading={update.isPending} okButtonProps={{disabled:selected.length===0}} cancelButtonProps={{disabled:update.isPending}} closable={!update.isPending} maskClosable={!update.isPending}><Text strong>{editing?.name}</Text><br/><Text type="secondary">{editing?.email}</Text><div style={{marginTop:20}}><Checkbox.Group value={selected} onChange={setSelected}><Space direction="vertical">{roleOptions.map(role=><Checkbox key={role} value={role}>{role}</Checkbox>)}</Space></Checkbox.Group></div>{!hasRole(me,'Owner')&&<Alert style={{marginTop:16}} type="warning" showIcon message="Owner role is protected" description="Only an Owner can grant or revoke Owner access."/>}</Modal></Layout.Content></Layout></Layout>;
}
