import { ArrowLeftOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Checkbox, Empty, Layout, Modal, Result, Space, Table, Tag, Typography, message } from 'antd';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { can, hasRole } from '../auth/permissions.js';
import { useCurrentUser } from '../auth/useAuth.js';
import { useAccessPermissions, useAccessRoles, useAccessUsers, useUpdateUserRoles } from './useAccessControl.js';
const {Title,Text}=Typography;
const roleNames=roles=>(roles||[]).map(r=>typeof r==='string'?r:r.name).filter(Boolean).sort();
const sameRoles=(a,b)=>JSON.stringify([...a].sort())===JSON.stringify([...b].sort());

export default function AccessControlPage(){
 const navigate=useNavigate(),{data:me}=useCurrentUser(),users=useAccessUsers(),roles=useAccessRoles(),permissions=useAccessPermissions(),update=useUpdateUserRoles(),[editing,setEditing]=useState(null),[selected,setSelected]=useState([]),[api,holder]=message.useMessage();
 const isOwner=hasRole(me,'Owner'),canManage=can(me,'roles.manage')&&can(me,'users.update');
 const roleOptions=useMemo(()=>{const names=(roles.data||[]).map(r=>r.name);return isOwner?names:names.filter(r=>r!=='Owner');},[roles.data,isOwner]);
 const currentRoles=roleNames(editing?.roles),hasChanges=Boolean(editing)&&!sameRoles(currentRoles,selected);
 const editingOwner=roleNames(editing?.roles).includes('Owner');
 const canManageTarget=canManage&&(isOwner||!editingOwner);
 const openEditor=u=>{if(!canManage)return;const targetRoles=roleNames(u.roles);if(!isOwner&&targetRoles.includes('Owner')){api.warning('Only an Owner can change access for an Owner account.');return;}setEditing(u);setSelected(targetRoles);};
 const closeEditor=()=>{if(!update.isPending){setEditing(null);setSelected([]);}};
 const save=()=>{if(!editing||!canManageTarget||selected.length===0||!hasChanges)return;const ownerChange=currentRoles.includes('Owner')!==selected.includes('Owner');Modal.confirm({title:ownerChange?'Confirm Owner access change':'Confirm role change',content:ownerChange?`You are changing Owner access for ${editing.name||editing.email}. Owner access controls the highest privilege level and lockout protection.`:`Update access roles for ${editing.name||editing.email}? Effective permissions change immediately.`,okText:ownerChange?'Confirm Owner change':'Update access',okButtonProps:ownerChange?{danger:true}:{},onOk:async()=>{try{await update.mutateAsync({userId:editing.id,roles:selected});api.success('User access updated');closeEditor();}catch(error){api.error(error?.response?.data?.message||'Access update failed.');}}});};
 const columns=[{title:'User',render:(_,u)=><div><Text strong>{u.name}</Text>{u.id===me?.id&&<Tag style={{marginLeft:8}}>You</Tag>}<br/><Text type="secondary">{u.email}</Text></div>},{title:'Roles',render:(_,u)=><Space wrap>{roleNames(u.roles).map(r=><Tag key={r}>{r}</Tag>)}</Space>},{title:'Actions',render:(_,u)=>canManage?<Button disabled={!isOwner&&roleNames(u.roles).includes('Owner')} onClick={()=>openEditor(u)}>Manage roles</Button>:<Text type="secondary">View only</Text>}];
 const matrixColumns=[{title:'Permission',dataIndex:'permission',fixed:'left'},...(roles.data||[]).map(role=>({title:role.name,key:role.name,align:'center',render:(_,row)=>role.permissions.includes(row.permission)?'✓':'—'}))];
 const matrix=(permissions.data||[]).map(permission=>({key:permission,permission}));
 const loadError=users.isError||roles.isError||permissions.isError;
 return <Layout className="workspace-shell">{holder}<Layout><Layout.Header className="workspace-header"><Space><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/')}>Knowledge library</Button><SafetyCertificateOutlined/><Text strong>Access Control</Text></Space></Layout.Header><Layout.Content className="workspace-content"><section className="library-heading"><div><Text className="eyebrow">ADMINISTRATION</Text><Title level={1} className="library-title">Access Control</Title><Text type="secondary">Manage workspace roles while the backend remains the authoritative security boundary.</Text></div></section><Alert type="info" showIcon message="Owner protection" description="Only Owners can manage the Owner role, and the final Owner cannot lose Owner access." style={{marginBottom:20}}/>{loadError?<Result status="warning" title="Access control data could not be loaded" subTitle="Your session may not have access to every administration catalogue, or the API request failed." extra={<Space><Button onClick={()=>navigate('/')}>Back to workspace</Button><Button type="primary" onClick={()=>{users.refetch();roles.refetch();permissions.refetch();}}>Try again</Button></Space>}/>:<><Card title="Users" className="state-card"><Table rowKey="id" loading={users.isLoading} dataSource={users.data?.data||[]} columns={columns} pagination={false} scroll={{x:700}} locale={{emptyText:<Empty description="No users found"/>}}/></Card><Card title="Permission matrix" className="state-card" style={{marginTop:20}}><Table rowKey="permission" loading={roles.isLoading||permissions.isLoading} dataSource={matrix} columns={matrixColumns} pagination={false} scroll={{x:800}} size="small"/></Card></>}<Modal title="Manage user roles" open={Boolean(editing)} onCancel={closeEditor} onOk={save} okText="Review & update" confirmLoading={update.isPending} okButtonProps={{disabled:selected.length===0||!hasChanges||!canManageTarget}} cancelButtonProps={{disabled:update.isPending}} closable={!update.isPending} maskClosable={!update.isPending}><Text strong>{editing?.name}</Text>{editing?.id===me?.id&&<Tag style={{marginLeft:8}}>You</Tag>}<br/><Text type="secondary">{editing?.email}</Text><div style={{marginTop:20}}><Checkbox.Group value={selected} onChange={setSelected} disabled={!canManageTarget}><Space direction="vertical">{roleOptions.map(role=><Checkbox key={role} value={role}>{role}</Checkbox>)}</Space></Checkbox.Group></div>{editingOwner&&<Alert style={{marginTop:16}} type="warning" showIcon message="Owner account" description="Owner access is protected by the backend. The final Owner cannot be demoted."/>}{!isOwner&&<Alert style={{marginTop:16}} type="warning" showIcon message="Owner role is protected" description="Only an Owner can grant, revoke, or modify Owner access."/>}</Modal></Layout.Content></Layout></Layout>;
}
