import { ArrowLeftOutlined, MailOutlined, PlusOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Checkbox, Empty, Form, Input, Layout, Modal, Result, Select, Space, Table, Tag, Typography, message } from 'antd';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { can, hasRole } from '../auth/permissions.js';
import { useCurrentUser } from '../auth/useAuth.js';
import { useAccessInvitations, useAccessPermissions, useAccessRoles, useAccessUsers, useInviteUser, useResendInvitation, useRevokeInvitation, useUpdateUserRoles } from './useAccessControl.js';
const {Title,Text}=Typography;
const roleNames=roles=>(roles||[]).map(r=>typeof r==='string'?r:r.name).filter(Boolean).sort();
const sameRoles=(a,b)=>JSON.stringify([...a].sort())===JSON.stringify([...b].sort());

export default function AccessControlPage(){
 const navigate=useNavigate(),{data:me}=useCurrentUser(),users=useAccessUsers(),roles=useAccessRoles(),permissions=useAccessPermissions(),invitations=useAccessInvitations(),update=useUpdateUserRoles(),invite=useInviteUser(),resend=useResendInvitation(),revoke=useRevokeInvitation(),[editing,setEditing]=useState(null),[selected,setSelected]=useState([]),[inviteOpen,setInviteOpen]=useState(false),[form]=Form.useForm(),[api,holder]=message.useMessage();
 const isOwner=hasRole(me,'Owner'),canManage=can(me,'roles.manage')&&can(me,'users.update');
 const roleOptions=useMemo(()=>{const names=(roles.data||[]).map(r=>r.name);return isOwner?names:names.filter(r=>r!=='Owner');},[roles.data,isOwner]);
 const currentRoles=roleNames(editing?.roles),hasChanges=Boolean(editing)&&!sameRoles(currentRoles,selected),editingOwner=currentRoles.includes('Owner'),canManageTarget=canManage&&(isOwner||!editingOwner);
 const openEditor=u=>{if(!canManage)return;const targetRoles=roleNames(u.roles);if(!isOwner&&targetRoles.includes('Owner')){api.warning('Only an Owner can change access for an Owner account.');return;}setEditing(u);setSelected(targetRoles);};
 const closeEditor=()=>{if(!update.isPending){setEditing(null);setSelected([]);}};
 const submitUpdate=async()=>{try{await update.mutateAsync({userId:editing.id,roles:selected});api.success('User access updated and the user was notified.');setEditing(null);setSelected([]);}catch(error){api.error(error?.response?.data?.message||Object.values(error?.response?.data?.errors||{})?.[0]?.[0]||'Access update failed.');}};
 const save=()=>{if(!editing||!canManageTarget||selected.length===0||!hasChanges||update.isPending)return;const ownerChange=currentRoles.includes('Owner')!==selected.includes('Owner');if(!ownerChange){void submitUpdate();return;}Modal.confirm({title:'Confirm Owner access change',content:`You are changing Owner access for ${editing.name||editing.email}. Owner access controls the highest privilege level and lockout protection.`,okText:'Confirm Owner change',okButtonProps:{danger:true},onOk:submitUpdate});};
 const sendInvite=async values=>{try{await invite.mutateAsync(values);api.success(`Invitation sent to ${values.email}`);setInviteOpen(false);form.resetFields();}catch(error){api.error(error?.response?.data?.message||Object.values(error?.response?.data?.errors||{})?.[0]?.[0]||'Invitation could not be sent.');}};
 const confirmRevoke=i=>Modal.confirm({title:'Revoke invitation?',content:`${i.email} will no longer be able to use this invitation link.`,okText:'Revoke',okButtonProps:{danger:true},onOk:async()=>{try{await revoke.mutateAsync(i.id);api.success('Invitation revoked');}catch(e){api.error(e?.response?.data?.message||'Could not revoke invitation.');}}});
 const doResend=async i=>{try{await resend.mutateAsync(i.id);api.success(`A new invitation was sent to ${i.email}`);}catch(e){api.error(e?.response?.data?.message||'Could not resend invitation.');}};
 const columns=[{title:'User',render:(_,u)=><div><Text strong>{u.name}</Text>{u.id===me?.id&&<Tag style={{marginLeft:8}}>You</Tag>}<br/><Text type="secondary">{u.email}</Text></div>},{title:'Roles',render:(_,u)=><Space wrap>{roleNames(u.roles).map(r=><Tag key={r}>{r}</Tag>)}</Space>},{title:'Actions',render:(_,u)=>canManage?<Button disabled={!isOwner&&roleNames(u.roles).includes('Owner')} onClick={()=>openEditor(u)}>Manage roles</Button>:<Text type="secondary">View only</Text>}];
 const inviteColumns=[{title:'Invitee',render:(_,i)=><div><Text strong>{i.name}</Text><br/><Text type="secondary">{i.email}</Text></div>},{title:'Roles',render:(_,i)=><Space wrap>{roleNames(i.roles).map(r=><Tag key={r}>{r}</Tag>)}</Space>},{title:'Status',dataIndex:'status',render:s=><Tag>{s}</Tag>},{title:'Expires',dataIndex:'expires_at',render:v=>v?new Date(v).toLocaleString():'—'},{title:'Actions',render:(_,i)=>canManage&&i.status!=='accepted'?<Space><Button disabled={i.status==='revoked'} onClick={()=>doResend(i)}>Resend</Button><Button danger disabled={i.status==='revoked'} onClick={()=>confirmRevoke(i)}>Revoke</Button></Space>:null}];
 const matrixColumns=[{title:'Permission',dataIndex:'permission',fixed:'left'},...(roles.data||[]).map(role=>({title:role.name,key:role.name,align:'center',render:(_,row)=>role.permissions.includes(row.permission)?'✓':'—'}))],matrix=(permissions.data||[]).map(permission=>({key:permission,permission}));
 const loadError=users.isError||roles.isError||permissions.isError||invitations.isError;
 return <Layout className="workspace-shell">{holder}<Layout><Layout.Header className="workspace-header"><Space><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/')}>Knowledge library</Button><SafetyCertificateOutlined/><Text strong>Access Control</Text></Space></Layout.Header><Layout.Content className="workspace-content"><section className="library-heading"><div><Text className="eyebrow">ADMINISTRATION</Text><Title level={1} className="library-title">Access Control</Title><Text type="secondary">Invite people, assign roles and review effective workspace permissions.</Text></div>{canManage&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setInviteOpen(true)}>Invite user</Button>}</section><Alert type="info" showIcon message="Secure invitations" description="Invited users set their own password from a time-limited email link. Owner access remains protected." style={{marginBottom:20}}/>{loadError?<Result status="warning" title="Access control data could not be loaded" subTitle="Your session may not have access to every administration catalogue, or the API request failed." extra={<Button onClick={()=>navigate('/')}>Back to workspace</Button>}/>:<><Card title="Users" className="state-card"><Table rowKey="id" loading={users.isLoading} dataSource={users.data?.data||[]} columns={columns} pagination={false} scroll={{x:700}} locale={{emptyText:<Empty description="No users found"/>}}/></Card><Card title={<Space><MailOutlined/>Invitations</Space>} className="state-card" style={{marginTop:20}}><Table rowKey="id" loading={invitations.isLoading} dataSource={invitations.data||[]} columns={inviteColumns} pagination={{pageSize:10}} scroll={{x:850}}/></Card><Card title="Permission matrix" className="state-card" style={{marginTop:20}}><Table rowKey="permission" loading={roles.isLoading||permissions.isLoading} dataSource={matrix} columns={matrixColumns} pagination={false} scroll={{x:800}} size="small"/></Card></>}
 <Modal title="Invite user" open={inviteOpen} onCancel={()=>!invite.isPending&&setInviteOpen(false)} footer={null} destroyOnHidden><Form form={form} layout="vertical" onFinish={sendInvite}><Form.Item name="name" label="Name" rules={[{required:true}]}><Input autoFocus/></Form.Item><Form.Item name="email" label="Email" rules={[{required:true},{type:'email'}]}><Input/></Form.Item><Form.Item name="roles" label="Workspace role(s)" rules={[{required:true}]} extra={!isOwner?'Owner can only be assigned by an Owner.':undefined}><Select mode="multiple" options={roleOptions.map(r=>({label:r,value:r}))}/></Form.Item><Alert type="info" showIcon message="No password is created here" description="The user receives a secure link and chooses their own password. The link expires after 7 days." style={{marginBottom:20}}/><Button type="primary" htmlType="submit" loading={invite.isPending} block>Send invitation</Button></Form></Modal>
 <Modal title="Manage user roles" open={Boolean(editing)} onCancel={closeEditor} onOk={save} okText="Save changes" confirmLoading={update.isPending} okButtonProps={{disabled:selected.length===0||!hasChanges||!canManageTarget}} cancelButtonProps={{disabled:update.isPending}} closable={!update.isPending} maskClosable={!update.isPending}><Text strong>{editing?.name}</Text>{editing?.id===me?.id&&<Tag style={{marginLeft:8}}>You</Tag>}<br/><Text type="secondary">{editing?.email}</Text><div style={{marginTop:20}}><Checkbox.Group value={selected} onChange={setSelected} disabled={!canManageTarget||update.isPending}><Space direction="vertical">{roleOptions.map(role=><Checkbox key={role} value={role}>{role}</Checkbox>)}</Space></Checkbox.Group></div>{editingOwner&&<Alert style={{marginTop:16}} type="warning" showIcon message="Owner account" description="Owner access is protected by the backend. The final Owner cannot be demoted."/>}{!isOwner&&<Alert style={{marginTop:16}} type="warning" showIcon message="Owner role is protected" description="Only an Owner can grant, revoke, or modify Owner access."/>}</Modal></Layout.Content></Layout></Layout>;
}
