import { Alert, Button, Card, Form, Input, Layout, Result, Space, Spin, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import http from '../../lib/http.js';
const { Title, Text } = Typography;

export default function AcceptInvitationPage(){
 const [params]=useSearchParams(),token=params.get('token')||'',email=params.get('email')||'', [invite,setInvite]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[done,setDone]=useState(false),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;(async()=>{if(!token||!email){setError('The invitation link is incomplete.');setLoading(false);return;}try{const{data}=await http.get('/api/invitations/accept',{params:{token,email}});if(active)setInvite(data.data);}catch(e){if(active)setError(e?.response?.data?.errors?.invitation?.[0]||e?.response?.data?.message||'This invitation is invalid or expired.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[token,email]);
 const submit=async values=>{setSubmitting(true);setError('');try{await http.post('/api/invitations/accept',{email,token,password:values.password,password_confirmation:values.password_confirmation});setDone(true);}catch(e){setError(e?.response?.data?.errors?.password?.[0]||e?.response?.data?.errors?.invitation?.[0]||e?.response?.data?.message||'The invitation could not be accepted.');}finally{setSubmitting(false);}};
 if(loading)return <Layout className="invitation-page"><Spin size="large"/></Layout>;
 if(done)return <Layout className="invitation-page"><Result status="success" title="Your account is ready" subTitle="Your workspace access has been activated. You can now sign in." extra={<Link to="/login"><Button type="primary">Sign in</Button></Link>}/></Layout>;
 if(!invite)return <Layout className="invitation-page"><Result status="error" title="Invitation unavailable" subTitle={error||'This invitation is invalid, expired, or revoked.'} extra={<Link to="/login"><Button>Back to sign in</Button></Link>}/></Layout>;
 return <Layout className="invitation-page"><Card className="invitation-card"><Space direction="vertical" size={4} className="invitation-heading"><Text className="login-eyebrow">MARJO TECH HUB</Text><Title level={2}>Accept invitation</Title><Text>You are joining as <strong>{invite.name}</strong> ({invite.email}).</Text><Text type="secondary">Access: {(invite.roles||[]).join(', ')}</Text></Space>{error&&<Alert className="login-alert" type="error" showIcon message={error}/>}<Form layout="vertical" onFinish={submit} style={{marginTop:24}} requiredMark="optional"><Form.Item label="Password" name="password" rules={[{required:true,message:'Enter a password.'},{min:10,message:'Use at least 10 characters.'},{pattern:/[a-z]/,message:'Include a lowercase letter.'},{pattern:/[A-Z]/,message:'Include an uppercase letter.'},{pattern:/\d/,message:'Include a number.'}]}><Input.Password size="large" autoComplete="new-password"/></Form.Item><Form.Item label="Confirm password" name="password_confirmation" dependencies={['password']} rules={[{required:true,message:'Confirm your password.'},({getFieldValue})=>({validator(_,value){if(!value||getFieldValue('password')===value)return Promise.resolve();return Promise.reject(new Error('Passwords do not match.'));}})]}><Input.Password size="large" autoComplete="new-password"/></Form.Item><Button type="primary" htmlType="submit" loading={submitting} size="large" block>Activate account</Button></Form><Text type="secondary" className="invitation-security-note">For security, this invitation can only be used once and expires automatically.</Text></Card></Layout>;
}
