import { Alert, Button, Card, Form, Input, Layout, Result, Space, Spin, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import http from '../../lib/http.js';
const { Title, Text } = Typography;

export default function AcceptInvitationPage(){
 const [params]=useSearchParams(),token=params.get('token')||'',email=params.get('email')||'', [invite,setInvite]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[done,setDone]=useState(false),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;(async()=>{if(!token||!email){setError('The invitation link is incomplete.');setLoading(false);return;}try{const{data}=await http.get('/api/invitations/accept',{params:{token,email}});if(active)setInvite(data.data);}catch(e){if(active)setError(e?.response?.data?.message||e?.response?.data?.errors?.invitation?.[0]||'This invitation is invalid or expired.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[token,email]);
 const submit=async values=>{setSubmitting(true);setError('');try{await http.post('/api/invitations/accept',{email,token,password:values.password,password_confirmation:values.password_confirmation});setDone(true);}catch(e){setError(e?.response?.data?.message||e?.response?.data?.errors?.invitation?.[0]||'The invitation could not be accepted.');}finally{setSubmitting(false);}};
 if(loading)return <Layout className="auth-shell"><Spin size="large"/></Layout>;
 if(done)return <Result status="success" title="Your account is ready" subTitle="Your workspace access has been activated. You can now sign in." extra={<Link to="/login"><Button type="primary">Sign in</Button></Link>}/>;
 if(!invite)return <Result status="error" title="Invitation unavailable" subTitle={error||'This invitation is invalid, expired, or revoked.'} extra={<Link to="/login"><Button>Back to sign in</Button></Link>}/>;
 return <Layout className="auth-shell"><Card style={{width:'100%',maxWidth:520}}><Space direction="vertical" size={4}><Text type="secondary">MARJO TECH HUB</Text><Title level={2}>Accept invitation</Title><Text>You are joining as <strong>{invite.name}</strong> ({invite.email}).</Text><Text type="secondary">Access: {(invite.roles||[]).join(', ')}</Text></Space>{error&&<Alert style={{marginTop:20}} type="error" showIcon message={error}/>}<Form layout="vertical" onFinish={submit} style={{marginTop:24}}><Form.Item label="Password" name="password" rules={[{required:true},{min:10,message:'Use at least 10 characters.'}]}><Input.Password autoComplete="new-password"/></Form.Item><Form.Item label="Confirm password" name="password_confirmation" dependencies={['password']} rules={[{required:true},{validator:(_,value)=>!value||value===undefined?Promise.resolve():Promise.resolve()},{validator:({getFieldValue},value)=>!value||getFieldValue('password')===value?Promise.resolve():Promise.reject(new Error('Passwords do not match.'))}]}><Input.Password autoComplete="new-password"/></Form.Item><Button type="primary" htmlType="submit" loading={submitting} block>Activate account</Button></Form></Card></Layout>;
}
