import { LockOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Form, Input, Space, Typography } from 'antd';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { resetPassword } from './api.js';
const { Title, Text }=Typography;
export default function ResetPasswordPage(){
 const [params]=useSearchParams(),[loading,setLoading]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(null); const token=params.get('token')||'',email=params.get('email')||'';
 const submit=async values=>{setLoading(true);setError(null);try{await resetPassword({...values,token,email});setDone(true);}catch(e){setError(e?.response?.data?.message||'The reset link is invalid or has expired.')}finally{setLoading(false)}};
 return <main className="login-page"><section className="login-intro"><div className="login-brand-mark">M</div><Text className="login-eyebrow">MARJO TECH HUB</Text><Title>Choose a new password.</Title><Text>Use a strong password you do not reuse elsewhere.</Text></section><section className="login-panel"><Card className="login-card" bordered={false}><Space direction="vertical" size={4} className="login-heading"><Title level={2}>Reset password</Title><Text type="secondary">{email||'Password recovery'}</Text></Space>{done?<><Alert type="success" showIcon message="Password reset successfully."/><Link to="/login"><Button type="primary" block style={{marginTop:20}}>Continue to sign in</Button></Link></>:<Form layout="vertical" size="large" onFinish={submit} requiredMark={false}>{!token||!email?<Alert type="error" showIcon message="This reset link is incomplete." style={{marginBottom:20}}/>:null}{error&&<Alert type="error" showIcon message={error} style={{marginBottom:20}}/>}<Form.Item name="password" label="New password" rules={[{required:true},{min:10,message:'Use at least 10 characters.'}]}><Input.Password prefix={<LockOutlined/>} autoComplete="new-password"/></Form.Item><Form.Item name="password_confirmation" label="Confirm new password" dependencies={['password']} rules={[{required:true},({getFieldValue})=>({validator(_,v){return !v||getFieldValue('password')===v?Promise.resolve():Promise.reject(new Error('Passwords do not match.'))}})]}><Input.Password prefix={<LockOutlined/>} autoComplete="new-password"/></Form.Item><Button type="primary" htmlType="submit" block disabled={!token||!email} loading={loading}>Reset password</Button></Form>}</Card></section></main>;
}
