import { SafetyCertificateOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Form, Input, Space, Typography } from 'antd';
import { useQueryClient } from '@tanstack/react-query';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { verifyTwoFactor } from './api.js';
import { AUTH_KEY } from './useAuth.js';
const {Title,Text}=Typography;
export default function TwoFactorPage(){const location=useLocation(),navigate=useNavigate(),client=useQueryClient(),[loading,setLoading]=useState(false),[error,setError]=useState(null);const challengeId=location.state?.challengeId;if(!challengeId)return <Navigate to="/login" replace/>;const submit=async({code})=>{setLoading(true);setError(null);try{const data=await verifyTwoFactor({challenge_id:challengeId,code});client.setQueryData(AUTH_KEY,data.user);navigate(location.state?.destination||'/',{replace:true});}catch(e){setError(e?.response?.data?.message||'Verification failed. Please retry.')}finally{setLoading(false)}};return <main className="login-page"><section className="login-intro"><div className="login-brand-mark">M</div><Text className="login-eyebrow">MARJO TECH HUB</Text><Title>One more security check.</Title><Text>We sent a six-digit one-time code to your account email.</Text></section><section className="login-panel"><Card className="login-card" bordered={false}><Space direction="vertical" size={4} className="login-heading"><SafetyCertificateOutlined style={{fontSize:28}}/><Title level={2}>Verify sign-in</Title><Text type="secondary">The code expires in 10 minutes and can only be used once.</Text></Space>{error&&<Alert type="error" showIcon message={error} style={{marginBottom:20}}/>}<Form layout="vertical" size="large" onFinish={submit} requiredMark={false}><Form.Item name="code" label="Verification code" rules={[{required:true,message:'Enter the six-digit code.'},{pattern:/^\d{6}$/,message:'Enter exactly six digits.'}]}><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="000000" autoFocus style={{letterSpacing:8,textAlign:'center',fontSize:20}}/></Form.Item><Button type="primary" htmlType="submit" block loading={loading}>Verify and sign in</Button><Button block type="text" onClick={()=>navigate('/login',{replace:true})}>Back to sign in</Button></Form></Card></section></main>}
