import { ApiOutlined, ArrowLeftOutlined, EditOutlined, GithubOutlined, GlobalOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Descriptions, Result, Skeleton, Space, Tag, Typography } from 'antd';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { can } from '../auth/permissions.js';
import { useCurrentUser } from '../auth/useAuth.js';
import ServiceModal from './ServiceModal.jsx';
import { useService } from './useServices.js';
import './services.css';
const {Title,Paragraph,Text,Link}=Typography; const lifecycleColor={production:'success',development:'processing',maintenance:'warning',deprecated:'default'};
const External=({href,icon,children})=>href?<Link href={href} target="_blank" rel="noreferrer"><Space>{icon}{children}</Space></Link>:<Text type="secondary">Not configured</Text>;
export default function ServiceDetailPage(){const {id}=useParams(),navigate=useNavigate(),{data:user}=useCurrentUser(),query=useService(id),[editing,setEditing]=useState(false);const service=query.data;if(query.isLoading)return <main className="services-page"><Skeleton active paragraph={{rows:8}}/></main>;if(query.isError)return <main className="services-page"><Result status="404" title="Service unavailable" subTitle="It may not exist or it may belong to another account." extra={<Button onClick={()=>navigate('/services')}>Back to catalog</Button>}/></main>;
 return <main className="services-page"><div className="services-nav"><Button icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/services')}>Projects & Services</Button>{can(user,'services.update')&&<Button type="primary" icon={<EditOutlined/>} onClick={()=>setEditing(true)}>Edit service</Button>}</div><section className="service-detail-hero"><div><Space wrap><Tag>{service.type}</Tag><Tag color={lifecycleColor[service.lifecycle]}>{service.lifecycle}</Tag></Space><Title level={1}>{service.name}</Title><Paragraph>{service.description||'No description has been added yet.'}</Paragraph></div></section>
 <Card className="service-overview-card" title="Overview"><Descriptions column={{xs:1,sm:1,md:2}}><Descriptions.Item label="Owner">{service.owner_label||'Personal ownership'}</Descriptions.Item><Descriptions.Item label="Slug"><Text code>{service.slug}</Text></Descriptions.Item><Descriptions.Item label="Repository"><External href={service.repository_url} icon={<GithubOutlined/>}>Open repository</External></Descriptions.Item><Descriptions.Item label="Production"><External href={service.production_url} icon={<GlobalOutlined/>}>Open production</External></Descriptions.Item><Descriptions.Item label="API base URL" span={2}><External href={service.api_base_url} icon={<ApiOutlined/>}>{service.api_base_url}</External></Descriptions.Item><Descriptions.Item label="Technology stack" span={2}><Space wrap>{service.technologies?.length?service.technologies.map(t=><Tag key={t}>{t}</Tag>):<Text type="secondary">Not configured</Text>}</Space></Descriptions.Item></Descriptions></Card>
 <div className="service-integration-grid"><Card title="Health"><Text type="secondary">Not configured</Text><Paragraph>Uptime, latency and incident history will attach here when the health integration is enabled.</Paragraph></Card><Card title="Security" extra={<SafetyCertificateOutlined/>}><Text type="secondary">Not configured</Text><Paragraph>Security findings are never fabricated. A future authorized scan can attach verified results here.</Paragraph></Card><Card title="APIs" extra={<ApiOutlined/>}><Text type="secondary">{service.api_base_url?'Base URL configured':'Not configured'}</Text><Paragraph>API Workbench integration will use explicit service metadata rather than hidden credentials.</Paragraph></Card><Card title="Documentation"><Text type="secondary">Not configured</Text><Paragraph>Runbooks, architecture notes and service documentation can be linked here later.</Paragraph></Card></div>
 <Alert type="info" showIcon message="Integration-ready, evidence-first" description="This page deliberately shows Not configured instead of fake health, security or reliability scores."/>
 <ServiceModal open={editing} service={service} onClose={()=>setEditing(false)}/></main>}
