import { DeleteOutlined, DownloadOutlined, EditOutlined, EyeOutlined, FileOutlined, PlusOutlined } from '@ant-design/icons';
import { Button, Card, Empty, Input, Pagination, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd';
import { useDeferredValue, useMemo, useState } from 'react';
import { downloadDocument, previewDocument } from './api.js';
import DocumentModal from './DocumentModal.jsx';
import { useDeleteDocument, useDocuments } from './useDocuments.js';
const { Title, Text }=Typography;
const size=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
export default function DocumentsPanel({categories=[],tags=[]}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState(null),[tag,setTag]=useState(null),[page,setPage]=useState(1),[modal,setModal]=useState({open:false,document:null}); const q=useDeferredValue(search.trim());
 const filters=useMemo(()=>({page,per_page:15,...(q?{q}:{}),...(category?{category_id:category}:{}),...(tag?{tag_id:tag}:{})}),[page,q,category,tag]); const query=useDocuments(filters),del=useDeleteDocument(),[api,holder]=message.useMessage(); const rows=query.data?.data||[],meta=query.data?.meta;
 const download=async(d,preview=false)=>{try{const r=preview?await previewDocument(d.id):await downloadDocument(d.id);const url=URL.createObjectURL(r.data);if(preview)window.open(url,'_blank','noopener,noreferrer');else{const a=document.createElement('a');a.href=url;a.download=d.original_name;document.body.appendChild(a);a.click();a.remove();}setTimeout(()=>URL.revokeObjectURL(url),60000);}catch{api.error(preview?'View failed.':'Download failed.')}};
 const remove=async d=>{try{await del.mutateAsync(d.id);api.success('Document deleted');}catch{api.error('Could not delete the document.')}};
 const columns=[{title:'Document',key:'doc',render:(_,d)=><Space><FileOutlined/><div><Text strong>{d.title}</Text><br/><Text type="secondary">{d.original_name}</Text></div></Space>},{title:'Type',dataIndex:'extension',render:x=><Tag>{x.toUpperCase()}</Tag>},{title:'Size',dataIndex:'size',render:size},{title:'Category',render:(_,d)=>d.category?.name||'—'},{title:'Tags',render:(_,d)=><Space wrap>{d.tags?.map(t=><Tag key={t.id}>{t.name}</Tag>)}</Space>},{title:'Security',render:(_,d)=>d.is_sensitive?<Tag color="warning">Sensitive</Tag>:<Text type="secondary">Standard</Text>},{title:'Actions',key:'actions',render:(_,d)=><Space wrap>{d.previewable&&<Button type="text" icon={<EyeOutlined/>} onClick={()=>download(d,true)}>View</Button>}<Button type="text" icon={<DownloadOutlined/>} onClick={()=>download(d)}>Download</Button><Button type="text" icon={<EditOutlined/>} onClick={()=>setModal({open:true,document:d})}>Edit</Button><Popconfirm title="Delete this document?" description="The private file and its metadata will be removed." okButtonProps={{danger:true}} onConfirm={()=>remove(d)}><Button type="text" danger icon={<DeleteOutlined/>}>Delete</Button></Popconfirm></Space>}];
 return <>{holder}<section className="library-heading"><div><Text className="eyebrow">PRIVATE KNOWLEDGE</Text><Title level={1} className="library-title">Documents</Title><Text type="secondary">Your private engineering notes, PDFs and reference files.</Text></div><Button type="primary" size="large" icon={<PlusOutlined/>} onClick={()=>setModal({open:true,document:null})}>Upload document</Button></section><div className="library-toolbar"><Input.Search allowClear value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search documents..." style={{maxWidth:360}}/><Select allowClear value={category} onChange={v=>{setCategory(v);setPage(1)}} placeholder="Category" options={categories.map(c=>({value:c.id,label:c.name}))} style={{minWidth:200}}/><Select allowClear value={tag} onChange={v=>{setTag(v);setPage(1)}} placeholder="Tag" options={tags.map(t=>({value:t.id,label:t.name}))} style={{minWidth:180}}/></div><Card className="state-card">{!query.isLoading&&!query.isError&&rows.length===0?<Empty description="No documents found."><Button type="primary" onClick={()=>setModal({open:true,document:null})}>Upload your first document</Button></Empty>:<Table rowKey="id" loading={query.isLoading} dataSource={rows} columns={columns} pagination={false} scroll={{x:1100}}/>}{query.isError&&<Empty description="We couldn't load your documents."><Button onClick={()=>query.refetch()}>Try again</Button></Empty>}</Card>{meta?.last_page>1&&<div className="library-pagination"><Pagination current={meta.current_page} total={meta.total} pageSize={meta.per_page} showSizeChanger={false} onChange={setPage}/></div>}<DocumentModal open={modal.open} document={modal.document} categories={categories} tags={tags} onClose={()=>setModal({open:false,document:null})}/></>;
}
