import { DeleteOutlined, DownloadOutlined, EditOutlined, EyeOutlined, FileOutlined, FolderAddOutlined, PlusOutlined, TagsOutlined } from '@ant-design/icons';
import { Button, Card, DatePicker, Empty, Form, Input, Modal, Pagination, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd';
import { useDeferredValue, useMemo, useState } from 'react';
import { can } from '../auth/permissions.js';
import { useCurrentUser } from '../auth/useAuth.js';
import CategoryModal from '../library/CategoryModal.jsx';
import { useCreateTag } from '../library/useLibrary.js';
import { downloadDocument, previewDocument } from './api.js';
import DocumentModal from './DocumentModal.jsx';
import { useDeleteDocument, useDocuments } from './useDocuments.js';
const { Title, Text }=Typography;
const { RangePicker }=DatePicker;
const size=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
function flattenCategories(categories=[],depth=0){return categories.flatMap(c=>[{value:c.id,label:`${'— '.repeat(depth)}${c.name}`},...flattenCategories(c.children,depth+1)]);}
export default function DocumentsPanel({categories=[],tags=[]}){
 const {data:user}=useCurrentUser();
 const canCreate=can(user,'documents.create'),canUpdate=can(user,'documents.update'),canDelete=can(user,'documents.delete'),canDownload=can(user,'documents.download'),canCreateCategory=can(user,'categories.create'),canCreateTag=can(user,'tags.create');
 const [search,setSearch]=useState(''),[category,setCategory]=useState(null),[tag,setTag]=useState(null),[dateRange,setDateRange]=useState(null),[page,setPage]=useState(1),[modal,setModal]=useState({open:false,document:null}),[categoryOpen,setCategoryOpen]=useState(false),[tagOpen,setTagOpen]=useState(false),[tagName,setTagName]=useState(''); const q=useDeferredValue(search.trim());
 const filters=useMemo(()=>({page,per_page:15,...(q?{q}:{}),...(category?{category_id:category}:{}),...(tag?{tag_id:tag}:{}),...(dateRange?.[0]?{date_from:dateRange[0].format('YYYY-MM-DD')}:{}),...(dateRange?.[1]?{date_to:dateRange[1].format('YYYY-MM-DD')}:{})}),[page,q,category,tag,dateRange]); const query=useDocuments(filters),del=useDeleteDocument(),createTag=useCreateTag(),[api,holder]=message.useMessage(); const rows=query.data?.data||[],meta=query.data?.meta;
 const download=async(d,preview=false)=>{if(!preview&&!canDownload)return;try{const r=preview?await previewDocument(d.id):await downloadDocument(d.id);const url=URL.createObjectURL(r.data);if(preview)window.open(url,'_blank','noopener,noreferrer');else{const a=document.createElement('a');a.href=url;a.download=d.original_name;document.body.appendChild(a);a.click();a.remove();}setTimeout(()=>URL.revokeObjectURL(url),60000);}catch{api.error(preview?'View failed.':'Download failed.')}};
 const remove=async d=>{if(!canDelete)return;try{await del.mutateAsync(d.id);api.success('Document deleted');}catch{api.error('Could not delete the document.')}};
 const onCategoryCreated=c=>{setCategory(c.id);setPage(1);api.success(`Category “${c.name}” created and selected`);};
 const createInlineTag=async()=>{if(!canCreateTag)return;const name=tagName.trim();if(!name||createTag.isPending)return;try{const created=await createTag.mutateAsync(name);setTag(created.id);setPage(1);setTagName('');setTagOpen(false);api.success(`Tag “${created.name}” created and selected`);}catch{api.error('Could not create the tag. Please retry.')}};
 const categoryDropdown=menu=><>{menu}{canCreateCategory&&<div style={{padding:8,borderTop:'1px solid #f0f0f0'}}><Button type="text" block icon={<FolderAddOutlined/>} onMouseDown={e=>e.preventDefault()} onClick={()=>setCategoryOpen(true)}>Add new category</Button></div>}</>;
 const tagDropdown=menu=><>{menu}{canCreateTag&&<div style={{padding:8,borderTop:'1px solid #f0f0f0'}}><Button type="text" block icon={<TagsOutlined/>} onMouseDown={e=>e.preventDefault()} onClick={()=>setTagOpen(true)}>Add new tag</Button></div>}</>;
 const columns=[{title:'Document',key:'doc',render:(_,d)=><Space><FileOutlined/><div><Text strong>{d.title}</Text><br/><Text type="secondary">{d.original_name}</Text></div></Space>},{title:'Type',dataIndex:'extension',render:x=><Tag>{x.toUpperCase()}</Tag>},{title:'Size',dataIndex:'size',render:size},{title:'Category',render:(_,d)=>d.category?.name||'—'},{title:'Tags',render:(_,d)=><Space wrap>{d.tags?.map(t=><Tag key={t.id}>{t.name}</Tag>)}</Space>},{title:'Security',render:(_,d)=>d.is_sensitive?<Tag color="warning">Sensitive</Tag>:<Text type="secondary">Standard</Text>},{title:'Actions',key:'actions',render:(_,d)=><Space wrap>{d.previewable&&<Button type="text" icon={<EyeOutlined/>} onClick={()=>download(d,true)}>View</Button>}{canDownload&&<Button type="text" icon={<DownloadOutlined/>} onClick={()=>download(d)}>Download</Button>}{canUpdate&&<Button type="text" icon={<EditOutlined/>} onClick={()=>setModal({open:true,document:d})}>Edit</Button>}{canDelete&&<Popconfirm title="Delete this document?" description="The private file and its metadata will be removed." okButtonProps={{danger:true}} onConfirm={()=>remove(d)}><Button type="text" danger icon={<DeleteOutlined/>}>Delete</Button></Popconfirm>}</Space>}];
 return <>{holder}<section className="library-heading"><div><Text className="eyebrow">PRIVATE KNOWLEDGE</Text><Title level={1} className="library-title">Documents</Title><Text type="secondary">Your private engineering notes, PDFs and reference files.</Text></div>{canCreate&&<Button type="primary" size="large" icon={<PlusOutlined/>} onClick={()=>setModal({open:true,document:null})}>Upload document</Button>}</section><div className="library-toolbar"><Input.Search allowClear value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search documents..." style={{maxWidth:320}}/><Select allowClear showSearch optionFilterProp="label" value={category} onChange={v=>{setCategory(v);setPage(1)}} placeholder="Category" options={flattenCategories(categories)} popupRender={categoryDropdown} style={{minWidth:200}}/><Select allowClear showSearch optionFilterProp="label" value={tag} onChange={v=>{setTag(v);setPage(1)}} placeholder="Tag" options={tags.map(t=>({value:t.id,label:t.name}))} popupRender={tagDropdown} style={{minWidth:180}}/><RangePicker value={dateRange} onChange={v=>{setDateRange(v);setPage(1)}} format="DD/MM/YYYY" placeholder={['Uploaded from','Uploaded to']} allowClear style={{minWidth:280}}/></div><Card className="state-card">{!query.isLoading&&!query.isError&&rows.length===0?<Empty description="No documents found.">{canCreate&&<Button type="primary" onClick={()=>setModal({open:true,document:null})}>Upload your first document</Button>}</Empty>:<Table rowKey="id" loading={query.isLoading} dataSource={rows} columns={columns} pagination={false} scroll={{x:1100}}/>}{query.isError&&<Empty description="We couldn't load your documents."><Button onClick={()=>query.refetch()}>Try again</Button></Empty>}</Card>{meta?.last_page>1&&<div className="library-pagination"><Pagination current={meta.current_page} total={meta.total} pageSize={meta.per_page} showSizeChanger={false} onChange={setPage}/></div>}{(canCreate||canUpdate)&&<DocumentModal open={modal.open} document={modal.document} categories={categories} tags={tags} onClose={()=>setModal({open:false,document:null})}/>} {canCreateCategory&&<CategoryModal open={categoryOpen} categories={categories} onCreated={onCategoryCreated} onClose={()=>setCategoryOpen(false)}/>} {canCreateTag&&<Modal title="Create new tag" open={tagOpen} onCancel={()=>{if(!createTag.isPending){setTagOpen(false);setTagName('')}}} onOk={createInlineTag} okText="Create tag" confirmLoading={createTag.isPending} cancelButtonProps={{disabled:createTag.isPending}} closable={!createTag.isPending} maskClosable={!createTag.isPending} destroyOnHidden><Form layout="vertical" requiredMark={false}><Form.Item label="Tag name" required extra="The new tag will be selected automatically as the active document filter."><Input autoFocus value={tagName} onChange={e=>setTagName(e.target.value)} onPressEnter={createInlineTag} placeholder="e.g. production" maxLength={60} disabled={createTag.isPending}/></Form.Item></Form></Modal>}</>;
}
