const SENSITIVE=/^(authorization|proxy-authorization|cookie|set-cookie|x-api-key|api-key|x-auth-token)$/i;
export const isSensitiveHeader=name=>SENSITIVE.test(String(name).trim());
export function parseRequestUrl(value){const raw=String(value).trim();if(!raw)return {valid:false,error:'Enter a request URL.'};try{const url=new URL(raw);if(!['http:','https:'].includes(url.protocol))return {valid:false,error:'Only HTTP and HTTPS URLs are supported.'};return {valid:true,url,secure:url.protocol==='https:',localhost:['localhost','127.0.0.1','::1'].includes(url.hostname)}}catch{return {valid:false,error:'Enter a valid absolute URL, including http:// or https://.'}}}
export function activeRows(rows=[]){return rows.filter(row=>row.enabled!==false&&String(row.key||'').trim());}
export function buildUrl(baseUrl,params=[]){const parsed=parseRequestUrl(baseUrl);if(!parsed.valid)throw new Error(parsed.error);const url=new URL(parsed.url);activeRows(params).forEach(({key,value})=>url.searchParams.append(String(key).trim(),String(value??'')));return url.toString()}
const shellQuote=value=>`'${String(value).replace(/'/g,`'\\''`)}'`;
export function generateCurl({method='GET',url,params=[],headers=[],bodyMode='none',body=''}){const finalUrl=buildUrl(url,params);const parts=['curl','--request',String(method).toUpperCase(),shellQuote(finalUrl)];activeRows(headers).forEach(({key,value})=>parts.push('--header',shellQuote(`${String(key).trim()}: ${String(value??'')}`)));if(bodyMode!=='none'&&body!=='')parts.push('--data-raw',shellQuote(body));return parts.join(' \\\n  ')}
export function generateFetch({method='GET',url,params=[],headers=[],bodyMode='none',body=''}){const finalUrl=buildUrl(url,params);const headerObject=Object.fromEntries(activeRows(headers).map(({key,value})=>[String(key).trim(),String(value??'')]));const options={method:String(method).toUpperCase()};if(Object.keys(headerObject).length)options.headers=headerObject;if(bodyMode!=='none'&&body!=='')options.body=body;return `fetch(${JSON.stringify(finalUrl)}, ${JSON.stringify(options,null,2)})\n  .then(response => response.text())\n  .then(console.log);`}
export function formatJsonBody(value){return JSON.stringify(JSON.parse(value),null,2)}
function tokenizeCurl(input){const tokens=[];let current='',quote=null,escaped=false;for(const char of String(input).trim()){if(escaped){current+=char;escaped=false;continue}if(char==='\\'&&quote!=="'"){escaped=true;continue}if(quote){if(char===quote)quote=null;else current+=char;continue}if(char==="'"||char==='"'){quote=char;continue}if(/\s/.test(char)){if(current){tokens.push(current);current=''}}else current+=char}if(quote)throw new Error('Unclosed quote in cURL input.');if(current)tokens.push(current);return tokens}
export function importCurl(input){const tokens=tokenizeCurl(input);if(tokens[0]!=='curl')throw new Error('Input must start with curl.');let method='GET',url='',body='',bodyMode='none';const headers=[];const unsupported=[];for(let i=1;i<tokens.length;i++){const token=tokens[i];if(token==='-X'||token==='--request'){method=(tokens[++i]||'GET').toUpperCase();continue}if(token==='-H'||token==='--header'){const raw=tokens[++i]||'';const idx=raw.indexOf(':');if(idx<1)throw new Error(`Invalid header: ${raw}`);headers.push({id:crypto.randomUUID(),key:raw.slice(0,idx).trim(),value:raw.slice(idx+1).trim(),enabled:true});continue}if(['-d','--data','--data-raw','--data-binary'].includes(token)){body=tokens[++i]??'';bodyMode='text';continue}if(token.startsWith('-')){unsupported.push(token);continue}if(!url)url=token;else unsupported.push(token)}if(!url)throw new Error('No URL found in cURL input.');try{JSON.parse(body);if(body)bodyMode='json'}catch{}return {method,url,headers,body,bodyMode,unsupported}}
export function requestSummary({method,url,params=[],headers=[],bodyMode='none'}){const parsed=parseRequestUrl(url);return {method:String(method).toUpperCase(),host:parsed.valid?parsed.url.host:'Invalid URL',secure:parsed.valid&&parsed.secure,localhost:parsed.valid&&parsed.localhost,params:activeRows(params).length,headers:activeRows(headers).length,body:bodyMode==='none'?'None':bodyMode.toUpperCase()}}
