import { ArrowLeftOutlined, CheckCircleOutlined, ClearOutlined, CodeOutlined, CopyOutlined, FieldTimeOutlined, FileProtectOutlined, LinkOutlined, LockOutlined, NumberOutlined, SearchOutlined, SafetyOutlined, ToolOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Empty, Input, InputNumber, Layout, Radio, Select, Space, Tag, Typography, message } from 'antd';
import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { decodeBase64,decodeUrl,encodeBase64,encodeUrl,formatJson,generateUuids,inspectJwt,minifyJson,sha256,timestampDetails } from './utils.js';
import './toolbox.css';
const {Title,Paragraph,Text}=Typography;
const tools=[
 {id:'json',name:'JSON Studio',category:'Data',icon:<CodeOutlined/>,description:'Format, minify and validate JSON safely in your browser.'},
 {id:'base64',name:'Base64',category:'Encoding',icon:<FileProtectOutlined/>,description:'UTF-8 safe Base64 encode and decode.'},
 {id:'url',name:'URL Encoding',category:'Encoding',icon:<LinkOutlined/>,description:'Encode or decode URL components without sending data anywhere.'},
 {id:'timestamp',name:'Timestamp',category:'Time',icon:<FieldTimeOutlined/>,description:'Convert Unix timestamps to ISO, UTC and local time.'},
 {id:'uuid',name:'UUID v4',category:'Generators',icon:<NumberOutlined/>,description:'Generate secure UUID v4 values with the Web Crypto API.'},
 {id:'hash',name:'SHA-256',category:'Security',icon:<LockOutlined/>,description:'Create a one-way SHA-256 digest locally. Hashing is not encryption.'},
 {id:'jwt',name:'JWT Inspector',category:'Security',icon:<SafetyOutlined/>,description:'Decode JWT header and payload locally without verifying the signature.'},
];
const toolIds=new Set(tools.map(t=>t.id));
function CopyButton({value,label='Copy'}){const [api,holder]=message.useMessage();const copy=async()=>{try{await navigator.clipboard.writeText(value??'');api.success('Copied')}catch{api.error('Clipboard unavailable')}};return <>{holder}<Button icon={<CopyOutlined/>} disabled={!value} onClick={copy}>{label}</Button></>}
function Workbench({title,description,input,result,onInput,actions,warning,placeholder='Paste or type here…'}){return <div className="tool-workbench"><div className="tool-pane"><div className="tool-pane-head"><div><Text strong>Input</Text><Text type="secondary">{description}</Text></div><Button type="text" icon={<ClearOutlined/>} onClick={()=>onInput('')} disabled={!input}>Clear</Button></div><Input.TextArea value={input} onChange={e=>onInput(e.target.value)} placeholder={placeholder} autoSize={{minRows:10,maxRows:18}} spellCheck={false}/><Space wrap className="tool-actions">{actions}</Space>{warning}</div><div className="tool-pane result-pane"><div className="tool-pane-head"><div><Text strong>{title}</Text><Text type="secondary">Result stays in this browser session.</Text></div><CopyButton value={result}/></div>{result?<pre className="tool-result"><code>{result}</code></pre>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="Your result will appear here"/>}</div></div>}
function JsonTool(){const [input,setInput]=useState(''),[result,setResult]=useState(''),[error,setError]=useState('');const run=fn=>{try{setResult(fn(input));setError('')}catch(e){setResult('');setError(e instanceof Error?e.message:'Invalid JSON')}};return <><Workbench title="JSON result" description="Valid JSON only." input={input} result={result} onInput={v=>{setInput(v);setError('')}} actions={<><Button type="primary" onClick={()=>run(formatJson)} disabled={!input}>Format</Button><Button onClick={()=>run(minifyJson)} disabled={!input}>Minify</Button></>} warning={error&&<Alert type="error" showIcon message="Invalid JSON" description={error}/>} /> </>}
function EncodingTool({kind}){const [input,setInput]=useState(''),[result,setResult]=useState(''),[error,setError]=useState('');const encode=kind==='base64'?encodeBase64:encodeUrl,decode=kind==='base64'?decodeBase64:decodeUrl;const run=fn=>{try{setResult(fn(input));setError('')}catch(e){setResult('');setError(e instanceof Error?e.message:'Could not transform this value.')}};return <Workbench title={kind==='base64'?'Base64 result':'URL result'} description="Transformation is performed locally." input={input} result={result} onInput={v=>{setInput(v);setError('')}} actions={<><Button type="primary" onClick={()=>run(encode)} disabled={!input}>Encode</Button><Button onClick={()=>run(decode)} disabled={!input}>Decode</Button></>} warning={error&&<Alert type="error" showIcon message="Transformation failed" description={error}/>} />}
function TimestampTool(){const [input,setInput]=useState(''),[unit,setUnit]=useState('auto'),[result,setResult]=useState(''),[error,setError]=useState('');const convert=()=>{try{const d=timestampDetails(input,unit);setResult(`Detected unit: ${d.unit}\nISO 8601: ${d.iso}\nUTC: ${d.utc}\nLocal: ${d.local}\nUnix seconds: ${d.seconds}\nUnix milliseconds: ${d.milliseconds}`);setError('')}catch(e){setResult('');setError(e.message)}};return <Workbench title="Converted time" description="Auto-detect seconds vs milliseconds or choose explicitly." input={input} result={result} onInput={v=>{setInput(v);setError('')}} placeholder="e.g. 1789200000" actions={<><Select value={unit} onChange={setUnit} options={[['auto','Auto detect'],['seconds','Seconds'],['milliseconds','Milliseconds']].map(([value,label])=>({value,label}))}/><Button type="primary" onClick={convert} disabled={!input}>Convert</Button></>} warning={error&&<Alert type="error" showIcon message={error}/>} />}
function UuidTool(){const [count,setCount]=useState(1),[result,setResult]=useState(''),[error,setError]=useState('');const generate=()=>{try{setResult(generateUuids(count).join('\n'));setError('')}catch(e){setError(e.message)}};return <div className="single-tool-card"><Card><Title level={4}>Generate secure UUID v4</Title><Paragraph type="secondary">Uses the browser Web Crypto API. Generate up to 20 at once.</Paragraph><Space wrap><InputNumber min={1} max={20} value={count} onChange={v=>setCount(v||1)}/><Button type="primary" onClick={generate}>Generate</Button><CopyButton value={result} label="Copy all"/></Space>{error&&<Alert type="error" showIcon message={error}/>} {result&&<pre className="tool-result"><code>{result}</code></pre>}</Card></div>}
function HashTool(){const [input,setInput]=useState(''),[result,setResult]=useState(''),[error,setError]=useState('');const run=async()=>{try{setResult(await sha256(input));setError('')}catch(e){setError(e.message)}};return <Workbench title="SHA-256 digest" description="One-way digest. This is not encryption and is not a password-storage tool." input={input} result={result} onInput={v=>{setInput(v);setError('')}} actions={<Button type="primary" onClick={run} disabled={!input}>Hash text</Button>} warning={<>{error&&<Alert type="error" showIcon message={error}/>}<Alert type="info" showIcon message="Security note" description="SHA-256 alone is not suitable for storing passwords. Use a dedicated password hashing algorithm on trusted server infrastructure."/></>} />}
function JwtTool(){const [input,setInput]=useState(''),[result,setResult]=useState(''),[error,setError]=useState('');const run=()=>{try{const data=inspectJwt(input);const claims=Object.entries(data.claims).map(([k,v])=>`${k}: ${v?.iso??'unreadable'}`).join('\n');setResult(`HEADER\n${JSON.stringify(data.header,null,2)}\n\nPAYLOAD\n${JSON.stringify(data.payload,null,2)}${claims?`\n\nREGISTERED TIME CLAIMS\n${claims}`:''}`);setError('')}catch(e){setResult('');setError(e.message)}};return <Workbench title="Decoded JWT" description="Header and payload are decoded locally. Signature is NOT verified." input={input} result={result} onInput={v=>{setInput(v);setError('')}} placeholder="eyJ…" actions={<Button type="primary" onClick={run} disabled={!input}>Decode token</Button>} warning={<><Alert type="warning" showIcon message="Decoded ≠ verified" description="This inspector does not verify the JWT signature, issuer, audience or trustworthiness. Never treat decoded claims as authenticated data."/>{error&&<Alert type="error" showIcon message={error}/>}</>} />}
function ToolBody({id}){if(id==='json')return <JsonTool/>;if(id==='base64'||id==='url')return <EncodingTool kind={id}/>;if(id==='timestamp')return <TimestampTool/>;if(id==='uuid')return <UuidTool/>;if(id==='hash')return <HashTool/>;if(id==='jwt')return <JwtTool/>;return null}
export default function ToolboxPage(){const navigate=useNavigate(),{toolId}=useParams(),[query,setQuery]=useState(''),[category,setCategory]=useState('All');const active=toolIds.has(toolId)?tools.find(t=>t.id===toolId):null;const categories=['All',...new Set(tools.map(t=>t.category))];const filtered=useMemo(()=>tools.filter(t=>(category==='All'||t.category===category)&&(!query.trim()||`${t.name} ${t.description} ${t.category}`.toLowerCase().includes(query.trim().toLowerCase()))),[query,category]);return <Layout className="toolbox-shell"><Layout.Header className="toolbox-header"><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>active?navigate('/toolbox'):navigate('/')}>{active?'All tools':'Workspace'}</Button><Space><ToolOutlined/><Text strong>Developer Toolbox</Text></Space></Layout.Header><Layout.Content className="toolbox-content">{active?<><section className="toolbox-title"><div><Text className="eyebrow">{active.category.toUpperCase()}</Text><Title>{active.name}</Title><Paragraph>{active.description}</Paragraph></div><Tag icon={<CheckCircleOutlined/>} color="success">Browser only</Tag></section><ToolBody id={active.id}/></>:<><section className="toolbox-hero"><div><Text className="eyebrow">DEVELOPER UTILITIES</Text><Title>Developer Toolbox</Title><Paragraph>Fast, privacy-first utilities for the transformations you use every day. Inputs stay in your browser and are never sent to the Marjo Tech Hub backend.</Paragraph></div><div className="privacy-badge"><SafetyOutlined/><div><Text strong>Local by design</Text><Text>No persistence · no API calls · no input in URLs</Text></div></div></section><div className="toolbox-toolbar"><Input allowClear prefix={<SearchOutlined/>} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search JSON, JWT, UUID, encoding…" aria-label="Search developer tools"/><Select value={category} onChange={setCategory} options={categories.map(value=>({value,label:value}))}/></div>{filtered.length?<div className="tool-grid">{filtered.map(tool=><Card key={tool.id} hoverable className="tool-card" onClick={()=>navigate(`/toolbox/${tool.id}`)}><div className="tool-icon">{tool.icon}</div><Space direction="vertical" size={6}><Tag>{tool.category}</Tag><Title level={4}>{tool.name}</Title><Paragraph type="secondary">{tool.description}</Paragraph><Text strong>Open tool →</Text></Space></Card>)}</div>:<Empty description="No tools match your search."/>}</>}</Layout.Content></Layout>}
