import { ArrowLeftOutlined, BranchesOutlined, CheckCircleOutlined, CopyOutlined, ExclamationCircleOutlined, SearchOutlined, SafetyOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Col, Drawer, Empty, Input, Layout, Row, Segmented, Select, Space, Tag, Typography, message } from 'antd';
import { useDeferredValue, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { gitCommands, gitWorkflows, stateLabels } from './data.js';
import './GitHandbook.css';

const {Title,Paragraph,Text}=Typography;
const categories=['All',...new Set(gitCommands.map(c=>c.category))];
const riskColor={safe:'success',caution:'warning',destructive:'error'};
const impactLabel={read:'READ',write:'CHANGES',none:'—'};

function StateModel({command}){const impact=command?.impact||{};return <div className="git-state-model">{Object.entries(stateLabels).map(([key,label],i)=><div className={`git-state-wrap ${impact[key]&&impact[key]!=='none'?'active':''}`} key={key}><div className="git-state-node"><Text strong>{label}</Text><span>{command?impactLabel[impact[key]||'none']:(i<3?'local state':'shared state')}</span></div>{i<3&&<span className="git-state-arrow">→</span>}</div>)}</div>}
function Code({children,onCopy}){return <div className="git-code"><code>{children}</code>{onCopy&&<Button type="text" icon={<CopyOutlined/>} onClick={()=>onCopy(children)}/>}</div>}

export default function GitHandbookPage(){
 const navigate=useNavigate(),[tab,setTab]=useState('Commands'),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[level,setLevel]=useState('All'),[selected,setSelected]=useState(null),[selectedWorkflow,setSelectedWorkflow]=useState(null);const q=useDeferredValue(query.trim().toLowerCase());const [api,holder]=message.useMessage();
 const commands=useMemo(()=>gitCommands.filter(c=>(category==='All'||c.category===category)&&(level==='All'||c.level===level)&&(!q||[c.command,c.purpose,c.explanation,c.category,...(c.related||[])].join(' ').toLowerCase().includes(q))),[q,category,level]);
 const copy=async text=>{try{await navigator.clipboard.writeText(text);api.success('Command copied')}catch{api.error('Clipboard unavailable')}};
 return <Layout className="git-handbook">{holder}<Layout.Header className="git-handbook-header"><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/')}>Knowledge library</Button><Space><BranchesOutlined/><Text strong>Git Handbook</Text></Space></Layout.Header><Layout.Content className="git-handbook-content">
  <section className="git-hero"><div><Text className="eyebrow">ENGINEERING PLAYBOOK</Text><Title>Git Handbook</Title><Paragraph>Understand Git as a state machine, not a list of commands. Learn what changes, when a command is safe, and how professional workflows recover when things go wrong.</Paragraph></div><div className="git-hero-badges"><Tag icon={<CheckCircleOutlined/>} color="success">Reference only</Tag><Tag icon={<SafetyOutlined/>}>No shell execution</Tag></div></section>
  <Card className="git-model-card"><div className="git-section-head"><div><Text strong>Visual Git model</Text><Paragraph type="secondary">Select a command to see which areas it reads or changes.</Paragraph></div>{selected&&<Tag color={riskColor[selected.risk]}>{selected.command}</Tag>}</div><StateModel command={selected}/></Card>
  <Segmented block value={tab} onChange={setTab} options={['Commands','Workflows','Safety model']}/>
  {tab==='Commands'&&<><div className="git-toolbar"><Input allowClear prefix={<SearchOutlined/>} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search git add, rebase, recovery..."/><Select value={category} onChange={setCategory} options={categories.map(v=>({value:v,label:v}))}/><Select value={level} onChange={setLevel} options={['All','Basic','Intermediate','Advanced'].map(v=>({value:v,label:v}))}/></div><div className="git-result-count"><Text type="secondary">{commands.length} practical commands</Text></div>{commands.length===0?<Empty description="No commands match these filters."/>:<div className="git-command-grid">{commands.map(c=><Card key={c.id} hoverable className={`git-command-card risk-${c.risk}`} onClick={()=>setSelected(c)}><div className="git-card-meta"><Tag>{c.category}</Tag><Tag>{c.level}</Tag><Tag color={riskColor[c.risk]}>{c.risk.toUpperCase()}</Tag></div><Title level={4}><code>{c.command}</code></Title><Paragraph>{c.purpose}</Paragraph><div className="git-impact-mini">{Object.entries(stateLabels).map(([k,label])=><span key={k} className={c.impact[k]&&c.impact[k]!=='none'?'on':''}>{label.replace(' Repository','').replace(' / Index','')}</span>)}</div></Card>)}</div>}</>}
  {tab==='Workflows'&&<div className="git-workflow-grid">{gitWorkflows.map(w=><Card key={w.id} hoverable onClick={()=>setSelectedWorkflow(w)}><Space direction="vertical" size={8}><Tag>{w.level}</Tag><Title level={4}>{w.title}</Title><Paragraph type="secondary">{w.summary}</Paragraph><Text strong>{w.steps.length} steps →</Text></Space></Card>)}</div>}
  {tab==='Safety model'&&<div className="git-safety-grid"><Card><Title level={4}>Local vs shared history</Title><Paragraph>Rewriting your own unshared commits can be useful. Once other people or automation depend on a commit, preserve history and prefer additive correction such as <code>git revert</code>.</Paragraph></Card><Card><Title level={4}>Fetch before integration</Title><Paragraph><code>git fetch</code> updates remote-tracking refs without changing your working tree. It gives you a chance to inspect before choosing merge, rebase or fast-forward pull.</Paragraph></Card><Card><Title level={4}>Force is exceptional</Title><Paragraph>If a rebased personal feature branch genuinely needs a force update, prefer <code>--force-with-lease</code>. It refuses to overwrite unexpected remote work.</Paragraph></Card><Card><Title level={4}>Recovery first</Title><Paragraph>Before destructive recovery, inspect <code>status</code>, <code>diff</code>, <code>log</code> and <code>reflog</code>. Preview <code>git clean</code> with <code>-n</code>.</Paragraph></Card></div>}
 </Layout.Content>
 <Drawer width={720} title={selected?.command} open={Boolean(selected)} onClose={()=>setSelected(null)}>{selected&&<div className="git-detail"><Space wrap><Tag>{selected.category}</Tag><Tag>{selected.level}</Tag><Tag color={riskColor[selected.risk]}>{selected.risk.toUpperCase()}</Tag></Space>{selected.risk==='destructive'&&<Alert type="error" showIcon icon={<ExclamationCircleOutlined/>} message="Destructive / history-rewriting operation" description="Verify repository state and recovery options before using this command."/>}<Title level={4}>Purpose</Title><Paragraph>{selected.explanation}</Paragraph><Title level={4}>Syntax</Title><Code onCopy={copy}>{selected.syntax}</Code><Title level={4}>When to use</Title><Paragraph>{selected.when}</Paragraph>{selected.avoid&&<><Title level={4}>When not to use</Title><Paragraph>{selected.avoid}</Paragraph></>}<Title level={4}>State impact</Title><StateModel command={selected}/><Title level={4}>Examples</Title>{selected.examples?.map(x=><Code key={x} onCopy={copy}>{x}</Code>)}{selected.flags?.length>0&&<><Title level={4}>Important flags</Title><ul>{selected.flags.map(x=><li key={x}>{x}</li>)}</ul></>}{selected.mistakes&&<Alert type="warning" showIcon message="Common mistake" description={selected.mistakes}/>} {selected.recovery&&<Alert type="info" showIcon message="Recovery guidance" description={selected.recovery}/>} {selected.related?.length>0&&<><Title level={4}>Related commands</Title><Space wrap>{selected.related.map(id=><Button size="small" key={id} onClick={()=>setSelected(gitCommands.find(c=>c.id===id)||selected)}>{gitCommands.find(c=>c.id===id)?.command||id}</Button>)}</Space></>}</div>}</Drawer>
 <Drawer width={680} title={selectedWorkflow?.title} open={Boolean(selectedWorkflow)} onClose={()=>setSelectedWorkflow(null)}>{selectedWorkflow&&<div className="git-workflow-detail"><Paragraph>{selectedWorkflow.summary}</Paragraph><div className="git-timeline">{selectedWorkflow.steps.map((step,i)=><div className="git-timeline-step" key={`${i}-${step}`}><span>{i+1}</span><Code onCopy={step.startsWith('git ')?copy:null}>{step}</Code></div>)}</div><Alert type="info" showIcon message="Read before running" description="These are reference workflows. Inspect your current branch, status and team policy before applying commands to a real repository."/></div>}</Drawer>
 </Layout>}
