import { AudioOutlined, CloseOutlined, DeleteOutlined, FileAddOutlined, SendOutlined, SmileOutlined, StopOutlined } from '@ant-design/icons';
import { Button, Input, Popover, Space, Tooltip, Typography } from 'antd';
import { useEffect, useRef, useState } from 'react';

const { Text }=Typography;
const EMOJIS=['😀','😂','😍','🥰','😊','😎','🤔','👍','👏','🙏','❤️','🔥','🎉','✅','🚀','💡','👋','💯','🙂','😉','😄','😭','😅','🤝'];
const formatTime=ms=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;

export default function RichComposer({value,onChange,onSend,onUpload,onError,disabled=false,busy=false}){
  const fileRef=useRef(null),recorderRef=useRef(null),streamRef=useRef(null),chunksRef=useRef([]),startedRef=useRef(0),timerRef=useRef(null),previewUrlRef=useRef(null);
  const [recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[voicePreview,setVoicePreview]=useState(null);
  const revokePreviewUrl=()=>{if(previewUrlRef.current){URL.revokeObjectURL(previewUrlRef.current);previewUrlRef.current=null;}};
  const clearVoicePreview=()=>{revokePreviewUrl();setVoicePreview(null);};
  useEffect(()=>()=>{clearInterval(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());revokePreviewUrl();},[]);
  const chooseFile=e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const kind=file.type.startsWith('image/')?'image':'file';onUpload({file,kind});};
  const startRecording=async()=>{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error('Voice recording is not supported by this browser.');clearVoicePreview();const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const preferred=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));const recorder=new MediaRecorder(stream,preferred?{mimeType:preferred}:undefined);recorderRef.current=recorder;chunksRef.current=[];recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data);};recorder.onstop=()=>{const duration=Date.now()-startedRef.current;const type=recorder.mimeType||chunksRef.current[0]?.type||'audio/webm';const blob=new Blob(chunksRef.current,{type});const extension=type.includes('ogg')?'ogg':'webm';const file=new File([blob],`voice-${Date.now()}.${extension}`,{type});stream.getTracks().forEach(t=>t.stop());streamRef.current=null;setRecording(false);setElapsed(0);revokePreviewUrl();const url=URL.createObjectURL(blob);previewUrlRef.current=url;setVoicePreview({file,durationMs:duration,url});};startedRef.current=Date.now();recorder.start(250);setRecording(true);timerRef.current=setInterval(()=>setElapsed(Date.now()-startedRef.current),250);};
  const stopRecording=()=>{clearInterval(timerRef.current);if(recorderRef.current?.state==='recording')recorderRef.current.stop();};
  const cancelRecording=()=>{clearInterval(timerRef.current);const recorder=recorderRef.current;if(recorder){recorder.onstop=null;if(recorder.state==='recording')recorder.stop();}streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setRecording(false);setElapsed(0);};
  const sendVoice=()=>{if(!voicePreview||busy)return;const payload=voicePreview;setVoicePreview(null);onUpload({file:payload.file,kind:'voice',durationMs:payload.durationMs});setTimeout(revokePreviewUrl,1000);};
  const emojiContent=<div className="emoji-grid">{EMOJIS.map(e=><button key={e} type="button" onClick={()=>onChange(value+e)}>{e}</button>)}</div>;
  if(recording)return <footer className="composer recording-composer"><div className="recording-state"><span className="recording-dot"/><Text strong>Recording voice</Text><Text type="secondary">{formatTime(elapsed)}</Text></div><Space><Tooltip title="Cancel"><Button danger type="text" icon={<CloseOutlined/>} onClick={cancelRecording}/></Tooltip><Button danger icon={<StopOutlined/>} onClick={stopRecording}>Stop</Button></Space></footer>;
  if(voicePreview)return <footer className="composer recording-composer"><div className="recording-state"><audio controls preload="metadata" src={voicePreview.url}/><Text type="secondary">{formatTime(voicePreview.durationMs)}</Text></div><Space><Tooltip title="Delete recording"><Button danger type="text" icon={<DeleteOutlined/>} onClick={clearVoicePreview}/></Tooltip><Button type="primary" icon={<SendOutlined/>} loading={busy} onClick={sendVoice}>Send voice</Button></Space></footer>;
  return <footer className="composer rich-composer"><div className="composer-tools"><Popover trigger="click" placement="topLeft" content={emojiContent}><Tooltip title="Emoji"><Button type="text" icon={<SmileOutlined/>} disabled={disabled||busy}/></Tooltip></Popover><Tooltip title="Attach file or image"><Button type="text" icon={<FileAddOutlined/>} disabled={disabled||busy} onClick={()=>fileRef.current?.click()}/></Tooltip><Tooltip title="Record voice"><Button type="text" icon={<AudioOutlined/>} disabled={disabled||busy} onClick={()=>startRecording().catch(e=>onError?.(e))}/></Tooltip><input ref={fileRef} hidden type="file" accept=".pdf,.docx,.txt,.md,image/jpeg,image/png,image/webp,image/gif" onChange={chooseFile}/></div><Input.TextArea aria-label="Message" autoSize={{minRows:1,maxRows:5}} value={value} onChange={e=>onChange(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();onSend();}}} placeholder={disabled?'You do not have permission to send messages.':'Write a message…'} disabled={disabled||busy} maxLength={5000}/><Button type="primary" shape="circle" size="large" onClick={onSend} loading={busy} disabled={disabled||!value.trim()} aria-label="Send message">➤</Button></footer>;
}
