import { ArrowLeftOutlined, CameraOutlined, DeleteOutlined, UserOutlined } from '@ant-design/icons';
import { Alert, Avatar, Button, Card, Col, Form, Input, Row, Space, Spin, Typography, Upload, message } from 'antd';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { deleteAvatar, fetchAvatar, getProfile, updateProfile, uploadAvatar } from './api.js';
const { Title, Text, Paragraph }=Typography; const { TextArea }=Input;
export default function ProfilePage(){
 const navigate=useNavigate(),client=useQueryClient(),[form]=Form.useForm(),[avatarUrl,setAvatarUrl]=useState(null),[api,holder]=message.useMessage();
 const profile=useQuery({queryKey:['profile'],queryFn:getProfile}); const save=useMutation({mutationFn:updateProfile}); const avatarUpload=useMutation({mutationFn:uploadAvatar}); const avatarDelete=useMutation({mutationFn:deleteAvatar});
 const user=profile.data;
 useEffect(()=>{if(user)form.setFieldsValue(user)},[user,form]);
 useEffect(()=>{let active=true,url=null;if(!user?.has_avatar){setAvatarUrl(null);return;}fetchAvatar().then(blob=>{if(!active)return;url=URL.createObjectURL(blob);setAvatarUrl(url)}).catch(()=>setAvatarUrl(null));return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[user?.has_avatar]);
 const sync=u=>{client.setQueryData(['profile'],u);client.setQueryData(['auth','me'],u)};
 const submit=async()=>{try{const u=await save.mutateAsync(await form.validateFields());sync(u);api.success('Profile updated');}catch(e){if(e?.errorFields)return;api.error(e?.response?.data?.message||'Could not update profile.')}};
 const beforeUpload=async file=>{try{const u=await avatarUpload.mutateAsync(file);sync(u);api.success('Avatar updated');}catch{api.error('Could not upload avatar. Use JPG, PNG or WebP up to 5 MB.')}return false;};
 const removeAvatar=async()=>{try{const u=await avatarDelete.mutateAsync();sync(u);setAvatarUrl(null);api.success('Avatar removed');}catch{api.error('Could not remove avatar.')}};
 if(profile.isLoading)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center'}}><Spin size="large"/></div>;
 return <>{holder}<div style={{minHeight:'100vh',background:'#f5f6f8'}}><div style={{height:72,background:'#fff',borderBottom:'1px solid #eee',display:'flex',alignItems:'center',padding:'0 32px'}}><Button type="text" icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/')}>Knowledge library</Button><Text strong style={{marginLeft:16}}>Marjo Tech Hub</Text></div><main style={{maxWidth:1050,margin:'0 auto',padding:'48px 24px'}}><Text className="eyebrow">ACCOUNT</Text><Title level={1}>My Profile</Title><Paragraph type="secondary">Manage your developer identity and profile information.</Paragraph>{profile.isError&&<Alert type="error" showIcon message="Could not load your profile"/>}<Row gutter={[24,24]}><Col xs={24} md={8}><Card><div style={{textAlign:'center'}}><Avatar size={128} src={avatarUrl} icon={<UserOutlined/>}/><Title level={3} style={{marginTop:18,marginBottom:2}}>{user?.name}</Title>{user?.username&&<Text type="secondary">@{user.username}</Text>}{user?.job_title&&<Paragraph style={{marginTop:8}}>{user.job_title}</Paragraph>}<Space direction="vertical" style={{width:'100%',marginTop:20}}><Upload accept="image/jpeg,image/png,image/webp" showUploadList={false} beforeUpload={beforeUpload}><Button block loading={avatarUpload.isPending} icon={<CameraOutlined/>}>{user?.has_avatar?'Change avatar':'Upload avatar'}</Button></Upload>{user?.has_avatar&&<Button block danger loading={avatarDelete.isPending} icon={<DeleteOutlined/>} onClick={removeAvatar}>Remove avatar</Button>}</Space></div></Card></Col><Col xs={24} md={16}><Card title="Profile information"><Form form={form} layout="vertical" onFinish={submit}><Row gutter={16}><Col xs={24} sm={12}><Form.Item name="first_name" label="First name" rules={[{required:true,message:'Enter your first name.'}]}><Input maxLength={80}/></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="last_name" label="Last name" rules={[{required:true,message:'Enter your last name.'}]}><Input maxLength={80}/></Form.Item></Col></Row><Form.Item name="username" label="Username" rules={[{required:true,message:'Choose a username.'},{min:3}]} extra="Letters, numbers, dots, hyphens and underscores."><Input addonBefore="@" maxLength={60}/></Form.Item><Form.Item name="job_title" label="Job title"><Input placeholder="e.g. Full-Stack Engineer" maxLength={120}/></Form.Item><Form.Item name="bio" label="Bio"><TextArea rows={5} maxLength={1000} showCount placeholder="A short description of your engineering focus..."/></Form.Item><Form.Item label="Email"><Input value={user?.email} disabled/></Form.Item><Button type="primary" htmlType="submit" size="large" loading={save.isPending}>Save profile</Button></Form></Card></Col></Row></main></div></>;
}
