import { AppstoreOutlined, AuditOutlined, CopyOutlined, DeleteOutlined, EditOutlined, EyeOutlined, FileTextOutlined, FolderAddOutlined, FolderOutlined, LogoutOutlined, MenuFoldOutlined, MenuUnfoldOutlined, MessageOutlined, PlusOutlined, SafetyCertificateOutlined, SearchOutlined, StarFilled, StarOutlined, UserOutlined } from '@ant-design/icons';
import { Avatar, Button, Card, Drawer, Dropdown, Empty, Input, Layout, Menu, Pagination, Popconfirm, Select, Skeleton, Space, Tag, Typography, message } from 'antd';
import { useDeferredValue, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { can } from './features/auth/permissions.js';
import { useCurrentUser, useLogout } from './features/auth/useAuth.js';
import { fetchAvatar } from './features/profile/api.js';
import CategoryModal from './features/library/CategoryModal.jsx';
import EntryModal from './features/library/EntryModal.jsx';
import { useCategories, useCreateTag, useDeleteEntry, useEntries, useTags, useToggleFavorite } from './features/library/useLibrary.js';

const { Header, Sider, Content } = Layout;
const { Title, Paragraph, Text } = Typography;
function categoryMenu(categories = []) { return categories.map((c) => ({ key:`category:${c.id}`, icon:<FolderOutlined/>, label:c.name, children:c.children?.length ? categoryMenu(c.children) : undefined })); }

export default function Workspace() {
  const [collapsed,setCollapsed]=useState(false), [selectedCategory,setSelectedCategory]=useState(null), [favoritesOnly,setFavoritesOnly]=useState(false), [selectedTag,setSelectedTag]=useState(null), [search,setSearch]=useState(''), [page,setPage]=useState(1), [newTagName,setNewTagName]=useState('');
  const [entryModal,setEntryModal]=useState({open:false,entry:null}), [detailEntry,setDetailEntry]=useState(null), [categoryOpen,setCategoryOpen]=useState(false), [avatarUrl,setAvatarUrl]=useState(null);
  const deferredSearch=useDeferredValue(search.trim());
  const {data:user}=useCurrentUser(), {data:categories=[],isLoading:categoriesLoading}=useCategories(), {data:tags=[]}=useTags();
  const canCreateEntry=can(user,'entries.create'),canUpdateEntry=can(user,'entries.update'),canDeleteEntry=can(user,'entries.delete'),canCreateCategory=can(user,'categories.create'),canCreateTag=can(user,'tags.create'),canViewDocuments=can(user,'documents.view'),canViewMessages=can(user,'messages.view'),canViewAccess=can(user,'users.view'),canViewActivity=can(user,'activity.view');
  useEffect(()=>setPage(1),[selectedCategory,favoritesOnly,selectedTag,deferredSearch]);
  useEffect(()=>{let active=true,url=null;if(!user?.has_avatar){setAvatarUrl(null);return;}fetchAvatar().then(blob=>{if(!active)return;url=URL.createObjectURL(blob);setAvatarUrl(url);}).catch(()=>{if(active)setAvatarUrl(null)});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[user?.has_avatar,user?.id]);
  const filters=useMemo(()=>({page,per_page:12,...(selectedCategory?{category_id:selectedCategory}:{}),...(favoritesOnly?{favorite:1}:{}),...(selectedTag?{tag_id:selectedTag}:{}),...(deferredSearch?{q:deferredSearch}:{})}),[page,selectedCategory,favoritesOnly,selectedTag,deferredSearch]);
  const entriesQuery=useEntries(filters), entries=entriesQuery.data?.data??[], meta=entriesQuery.data?.meta;
  const deleteEntry=useDeleteEntry(), toggleFavorite=useToggleFavorite(), createTag=useCreateTag(), logout=useLogout(), navigate=useNavigate();
  const [messageApi,contextHolder]=message.useMessage();
  const initials=user?.name?.split(/\s+/).slice(0,2).map(p=>p[0]).join('').toUpperCase()||'U';
  const menuItems=useMemo(()=>[
    {key:'all',icon:<AppstoreOutlined/>,label:'All entries'},
    {key:'favorites',icon:<StarOutlined/>,label:'Favorites'},
    ...(canViewDocuments?[{key:'documents',icon:<FileTextOutlined/>,label:'Documents'}]:[]),
    ...(canViewMessages?[{key:'messages',icon:<MessageOutlined/>,label:'Messages'}]:[]),
    ...(canViewActivity?[{key:'activity',icon:<AuditOutlined/>,label:'Activity'}]:[]),
    ...(canViewAccess?[{key:'access-control',icon:<SafetyCertificateOutlined/>,label:'Access Control'}]:[]),
    {type:'divider'},
    ...categoryMenu(categories)
  ],[categories,canViewDocuments,canViewMessages,canViewActivity,canViewAccess]);
  const selectMenu=({key})=>{if(key==='documents'){navigate('/documents');return;}if(key==='messages'){navigate('/messages');return;}if(key==='activity'){navigate('/activity');return;}if(key==='access-control'){navigate('/access-control');return;}setFavoritesOnly(key==='favorites');setSelectedCategory(key.startsWith('category:')?Number(key.replace('category:','')):null);};
  const signOut=async()=>{await logout.mutateAsync();navigate('/login',{replace:true})};
  const copy=async(entry)=>{try{await navigator.clipboard.writeText(entry.content);messageApi.success(`Copied “${entry.title}”`)}catch{messageApi.error('Clipboard access failed. Copy the content manually.')}};
  const remove=async(entry)=>{try{await deleteEntry.mutateAsync(entry.id);if(detailEntry?.id===entry.id)setDetailEntry(null);messageApi.success('Entry deleted')}catch{messageApi.error('Could not delete the entry. Please retry.')}};
  const favorite=async(entry)=>{try{await toggleFavorite.mutateAsync({id:entry.id,active:entry.is_favorite});if(detailEntry?.id===entry.id)setDetailEntry({...entry,is_favorite:!entry.is_favorite})}catch{messageApi.error('Could not update the favorite. Please retry.')}};
  const addTag=async()=>{if(!canCreateTag)return;const name=newTagName.trim();if(!name||createTag.isPending)return;try{await createTag.mutateAsync(name);setNewTagName('');messageApi.success(`Tag “${name}” is ready`)}catch{messageApi.error('Could not create the tag.')}};
  const accountMenu={items:[{key:'identity',label:<div><Text strong>{user?.name}</Text><br/><Text type="secondary">{user?.username?`@${user.username}`:user?.email}</Text></div>,disabled:true},{type:'divider'},{key:'profile',icon:<UserOutlined/>,label:'My Profile',onClick:()=>navigate('/profile')},{key:'logout',icon:<LogoutOutlined/>,label:'Sign out',danger:true,onClick:signOut}]};
  const selectedKey=favoritesOnly?'favorites':selectedCategory?`category:${selectedCategory}`:'all';

  return <Layout className="workspace-shell">{contextHolder}<Sider className="workspace-sider" width={270} collapsedWidth={76} collapsed={collapsed} trigger={null} breakpoint="lg" onBreakpoint={setCollapsed}>
    <div className="brand-block"><div className="brand-mark">M</div>{!collapsed&&<div><Text className="brand-name">Marjo Tech Hub</Text><Text className="brand-caption">Engineering workspace</Text></div>}</div>{!collapsed&&canCreateCategory&&<div className="sidebar-actions"><Button icon={<FolderAddOutlined/>} block onClick={()=>setCategoryOpen(true)}>New category</Button></div>}{categoriesLoading?<div className="sidebar-loading"><Skeleton active paragraph={{rows:5}} title={false}/></div>:<Menu mode="inline" selectedKeys={[selectedKey]} items={menuItems} className="workspace-menu" onClick={selectMenu}/>}</Sider>
    <Layout><Header className="workspace-header"><Button type="text" className="collapse-button" icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(v=>!v)}/><Input allowClear value={search} onChange={e=>setSearch(e.target.value)} className="global-search" prefix={<SearchOutlined/>} placeholder="Search your engineering library..." aria-label="Search workspace"/><Dropdown menu={accountMenu} placement="bottomRight" trigger={['click']}><Button type="text" className="account-button"><Space><Avatar className="user-avatar" src={avatarUrl}>{initials}</Avatar><span className="account-name">{user?.name}</span></Space></Button></Dropdown></Header>
    <Content className="workspace-content"><section className="library-heading"><div><Text className="eyebrow">KNOWLEDGE LIBRARY</Text><Title level={1} className="library-title">{favoritesOnly?'Favorites':deferredSearch?'Search results':selectedCategory?'Category entries':'All entries'}</Title><Paragraph className="hero-copy">Fast access to the engineering knowledge you actually reuse.</Paragraph></div>{canCreateEntry&&<Button type="primary" size="large" icon={<PlusOutlined/>} onClick={()=>setEntryModal({open:true,entry:null})}>Add entry</Button>}</section>
    <div className="library-toolbar"><Select allowClear value={selectedTag} onChange={setSelectedTag} placeholder="Filter by tag" options={tags.map(t=>({value:t.id,label:`${t.name} (${t.entries_count??0})`}))} style={{minWidth:210}}/>{canCreateTag&&<Input.Search value={newTagName} onChange={e=>setNewTagName(e.target.value)} placeholder="Create a tag and press Enter" enterButton={<Button type="primary" loading={createTag.isPending}>Add tag</Button>} onSearch={addTag} onPressEnter={addTag} disabled={createTag.isPending} style={{maxWidth:340}}/>}</div>
    {entriesQuery.isLoading&&<div className="entry-grid">{[1,2,3].map(k=><Card key={k} className="entry-card"><Skeleton active/></Card>)}</div>}
    {entriesQuery.isError&&<Card className="state-card"><Empty description="We couldn't load your library."><Button type="primary" onClick={()=>entriesQuery.refetch()} loading={entriesQuery.isFetching}>Try again</Button></Empty></Card>}
    {!entriesQuery.isLoading&&!entriesQuery.isError&&entries.length===0&&<Card className="state-card"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={favoritesOnly?'No favorites yet.':deferredSearch?'No entries match your search.':'No entries here yet.'}>{canCreateEntry&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setEntryModal({open:true,entry:null})}>Create an entry</Button>}</Empty></Card>}
    {!entriesQuery.isLoading&&entries.length>0&&<><section className="entry-grid">{entries.map(entry=>{const actions=[<Button key="view" type="text" icon={<EyeOutlined/>} onClick={()=>setDetailEntry(entry)}>Open</Button>,<Button key="copy" type="text" icon={<CopyOutlined/>} onClick={()=>copy(entry)}>Copy</Button>];if(canUpdateEntry)actions.push(<Button key="edit" type="text" icon={<EditOutlined/>} onClick={()=>setEntryModal({open:true,entry})}>Edit</Button>);if(canDeleteEntry)actions.push(<Popconfirm key="delete" title="Delete this entry?" description="This action cannot be undone." okText="Delete" okButtonProps={{danger:true}} onConfirm={()=>remove(entry)}><Button type="text" danger icon={<DeleteOutlined/>}/></Popconfirm>);return <Card key={entry.id} className="entry-card" hoverable actions={actions}><div className="entry-card-top"><Space size={6} wrap><Tag>{entry.type}</Tag>{entry.language&&<Tag>{entry.language}</Tag>}{entry.is_sensitive&&<Tag color="warning">Sensitive</Tag>}</Space><Button type="text" loading={toggleFavorite.isPending&&toggleFavorite.variables?.id===entry.id} aria-label={entry.is_favorite?'Remove favorite':'Add favorite'} icon={entry.is_favorite?<StarFilled/>:<StarOutlined/>} onClick={()=>favorite(entry)}/></div><Title level={4} className="entry-title" onClick={()=>setDetailEntry(entry)}>{entry.title}</Title>{entry.description&&<Paragraph type="secondary" ellipsis={{rows:2}}>{entry.description}</Paragraph>}<Space size={[4,4]} wrap>{entry.tags?.map(tag=><Tag key={tag.id} onClick={()=>setSelectedTag(tag.id)}>{tag.name}</Tag>)}</Space><pre className="entry-preview"><code>{entry.content}</code></pre></Card>;})}</section>{meta?.last_page>1&&<div className="library-pagination"><Pagination current={meta.current_page} pageSize={meta.per_page} total={meta.total} showSizeChanger={false} onChange={setPage} showTotal={total=>`${total} entries`}/></div>}</>}
    </Content></Layout>
    {canCreateEntry||canUpdateEntry?<EntryModal open={entryModal.open} entry={entryModal.entry} categories={categories} defaultCategoryId={selectedCategory} onClose={()=>setEntryModal({open:false,entry:null})}/>:null}{canCreateCategory&&<CategoryModal open={categoryOpen} categories={categories} onClose={()=>setCategoryOpen(false)}/>} 
    <Drawer title={detailEntry?.title} width={620} open={Boolean(detailEntry)} onClose={()=>setDetailEntry(null)} extra={detailEntry&&<Space><Button loading={toggleFavorite.isPending} icon={detailEntry.is_favorite?<StarFilled/>:<StarOutlined/>} onClick={()=>favorite(detailEntry)}>{detailEntry.is_favorite?'Favorited':'Favorite'}</Button><Button type="primary" icon={<CopyOutlined/>} onClick={()=>copy(detailEntry)}>Copy</Button></Space>}>{detailEntry&&<div className="entry-detail"><Space wrap><Tag>{detailEntry.type}</Tag>{detailEntry.language&&<Tag>{detailEntry.language}</Tag>}{detailEntry.is_sensitive&&<Tag color="warning">Sensitive</Tag>}</Space>{detailEntry.description&&<Paragraph className="detail-description">{detailEntry.description}</Paragraph>}<Space wrap>{detailEntry.tags?.map(t=><Tag key={t.id}>{t.name}</Tag>)}</Space><pre className="detail-code"><code>{detailEntry.content}</code></pre><Text type="secondary">Updated {detailEntry.updated_at?new Date(detailEntry.updated_at).toLocaleString():'recently'}</Text></div>}</Drawer>
  </Layout>;
}
